name: Brandon Cromer
description: Just a place to do things and stuff.
url: http://cromers.net
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sass-converter
  - kramdown
  - rouge
markdown: kramdown
highlighter: rouge
timezone: America/Detroit
safe: false
paginate: 5
paginate_path: "/blog/page:num/"
